springdoc:
  packages-to-scan: com.solace.maas.ep.runtime.agent.scanManager.rest
  api-docs:
    path: /docs/runtime-agent
  swagger-ui:
    path: runtime-agent/swagger-ui.html
server:
  port: 8180
spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
    password: password
    driver-class-name: org.h2.Driver
    username: sa
camel:
  springboot:
    use-mdc-logging: true
eventPortal:
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:f5w5j7ed69c}
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}
  gateway:
    id: g527g4hnak7
    name: US East EVMR
    messaging:
      standalone: false
      rtoSession: false
      enableHeartbeats: true
      testHeartbeats: true
      connections:
      - name: eventPortalGateway
        authenticationType: ${EP_GATEWAY_AUTH:basicAuthentication}
        msgVpn: ${EP_GATEWAY_MSGVPN:runtime-agent-evmr}
        url: ${EP_GATEWAY_URL:tcps://mrg1qbaza00z0.messaging.solace.cloud:55443}
        users:
        - clientName: client_f5w5j7ed69c
          name: messaging1
          password: BMvUCsvxTvy!}xm=18QFwbBg
          username: ${EP_GATEWAY_USERNAME:maasdev-67tr8tktyr-f5w5j7ed69c}
  organizationId: ${EP_ORGANIZATION_ID:maasdev}
plugins:
  messagingServices:
  - id: ojvoelkrj2w
    type: solace
    name: abdullah-empty-broker
    connections:
    - name: abdullah-empty-broker
      url: https://mrurvyzpl9y98.messaging.solace.cloud:943
      properties:
      - name: msgVpn
        value: abdullah-empty-broker
      - name: sempPageSize
        value: 100
      authentication:
      - protocol: SEMP
        credentials:
        - type: USERNAME_PASSWORD
          source: ENVIRONMENT_VARIABLE
          operations:
          - name: ALL
          properties:
          - name: username
            value: abdullah-empty-broker-admin
          - name: password
            value: o51gh1h1625bsrfi2ggqvanudt
        properties:
        - name: type
          value: basicAuthentication
  - id: 5ujuqshtbuz
    type: kafka
    name: confluent Kafka cluster
    connections:
    - name: confluent Kafka cluster
      url: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      authentication:
      - credentials:
  - id: ebp6alma25g
    type: kafka
    name: gregKafkaNoAuth
    connections:
    - name: kafkaNoAuthConnection
      url: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:12091}
      authentication:
      - protocol: PLAINTEXT
        credentials:
        - type: USERNAME_PASSWORD
          source: ENVIRONMENT_VARIABLE
          operations:
          - name: ALL
  - id: 37o1yj73k9m
    type: solace
    name: Gregs ivmr
    connections:
    - name: Gregs ivmr
      url: https://mr-connection-ofdjrwxkphk.messaging.solace.cloud:943
      properties:
      - name: msgVpn
        value: gregs-ivmr
      - name: sempPageSize
        value: 100
      authentication:
      - protocol: SEMP
        credentials:
        - type: USERNAME_PASSWORD
          source: ENVIRONMENT_VARIABLE
          operations:
          - name: ALL
          properties:
          - name: username
            value: gregs-ivmr-admin
          - name: password
            value: maacmpghig094gn1ld3ukd026h
        properties:
        - name: type
          value: basicAuthentication
  - id: df7efq67k45
    type: kafka
    name: kafkaMtlsService
    connections:
    - name: kafkaMTLSConnection
      url: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:11091}
      authentication:
      - protocol: SSL
        credentials:
        - type: mtls
          source: ENVIRONMENT_VARIABLE
          operations:
          - name: ALL
          properties:
          - name: ssl.truststore.location
            value: /Users/gmeldrum/Downloads/kafka.appSA.truststore.jks
          - name: ssl.truststore.password
            value: ${TRUSTSTORE_PASSWORD}
          - name: ssl.keystore.password
            value: ${KEYSTORE_PASSWORD}
          - name: ssl.keystore.location
            value: /Users/gmeldrum/Downloads/kafka.appSA.keystore.jks
          - name: ssl.key.password
            value: ${KEY_PASSWORD}
