replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: "868978040651.dkr.ecr.us-east-1.amazonaws.com"
  name: "runtime-agent"
  tag: ""
maas:
  id: ""
  version: ""
  instanceId: ""
  prefix: ""
  dbPrefix: ""
  domain: ""
  profile: ""
  githash: ""
  branch: ""
  buildTimestamp: ""
  acceptRequests: false
  livenessProbe:
    enabled: true
    path: /api/v0/component/spring/health/liveness
  readinessProbe:
    enabled: true
    path: /api/v0/component/spring/health/readiness
  startupProbe:
    enabled: true
    path: /api/v0/component/spring/health/readiness
  audit:
    enabled: false
  heartbeats:
    enabled: true
    svcType: "runtime-agent"
    originId: "RA-1"
  service:
    port: 8180
  preStop:
    enabled: false
resources:
  limits:
    cpu: "512m"
    memory: "2Gi"
  requests:
    cpu: "512m"
    memory: "2Gi"
securityContext:
  enabled: true
  fsGroup: "10002"
  runAsUser: "10001"
db:
  connectionString: ""
  name: ""
  username: ""
  password: ""
  maximumPoolSize: ""
  testWhileIdle: true
  validationQuery: "SELECT 1"

vmr:
  host: ""
  username: ""
  password: ""
  vpnname: ""
  mailbox: ""
  clientName: ""

datadog:
  flavor: "datadog"
  statsdPort: 8125
  isEnabled: "True"
  agentHost: "datadog-agent"

runtime:
  accessKeyId: ""
  secretAccessKey: ""
  jwtSecret: ""
  max_http_header_size: "4MB"
  tomcat:
    max_threads: 200
    accept_count: 100
  caching:
    organizations:
      enabled: true
      timeUnit: "hours"
      duration: 1
      maximumSize: 1000
  runDbScriptsOnStartup: "true"
